locale                   : "en-US"
title                    : "Conor | Robotics & AI Recruiter"
title_separator          : "-"
name                     : "Conor"
description              : "HR ＆ Recruiter specializing in Robotics and AI"
url                      : "https://conor-qbo.github.io"
baseurl                  : ""
repository               : "Conor-Qbo/Conor-Qbo.github.io"

author:
  name              : "Conor"
  bio               : "HR | Robotics & AI Talent<br>—— ——<br>Interesting sharing <br>authentic information<br>有趣的分享，真实的信息。"
  avatar            : "Qbo.jpg"
  uri               : "https://www.xiaohongshu.com/user/profile/5df428250000000001007daa"
  email             : "xfire19580517@163.com"
  github            : "Conor-Qbo"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Conor-Qbo"
    - label: "小红书"
      icon: "fab fa-weibo"
      url: "https://www.xiaohongshu.com/user/profile/5df428250000000001007daa"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:xfire-hr@outlook.com"
    - label: "公众号：conorHR"
      icon: "fab fa-weixin"
      url: "#"
    - label: "公众号：清bo"
      icon: "fab fa-weixin"
      url: "https://mp.weixin.qq.com/s/WuhSKm5XVp3WeJWA4VSMnQ"

      
breadcrumbs              : false
words_per_minute         : 160
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false
atom_feed:
  hide                   : true

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: false
  publications:
    output: false
  portfolio:
    output: false
  talks:
    output: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
